#!/usr/bin/env python3
"""Generate src/core/sz_error_map.inc from the installed szerrors.json.

Emits a sorted std::pair<int64_t, SzErrorClass> table mapping Senzing error code
-> exception class. No codes/classes are hardcoded in C++ -- they all come from
the Senzing-provided szerrors.json. Mirrors the C# generated SzExceptionMapper:
codes that map to the base SzException (class "SzError") are OMITTED so the base
class is the implicit default for any unmapped code.

Usage: gen_errors.py <szerrors.json> <output sz_error_map.inc>
"""

import json
import sys


# Maps the szerrors.json `class` field (which uses the *Error suffix naming) to
# the SzErrorClass enumerator used by the C++ mapper. Derived directly from the
# class names present in szerrors.json -> the SzException subclass tree.
CLASS_TO_ENUM = {
    "SzError": "Base",                       # default -> base SzException (omitted)
    "SzBadInputError": "BadInput",
    "SzNotFoundError": "NotFound",
    "SzUnknownDataSourceError": "UnknownDataSource",
    "SzConfigurationError": "Configuration",
    "SzReplaceConflictError": "ReplaceConflict",
    "SzRetryTimeoutExceededError": "RetryTimeoutExceeded",
    "SzDatabaseConnectionLostError": "DatabaseConnectionLost",
    "SzDatabaseTransientError": "DatabaseTransient",
    "SzDatabaseError": "Database",
    "SzLicenseError": "License",
    "SzNotInitializedError": "NotInitialized",
    "SzUnhandledError": "Unhandled",
}


def main() -> int:
    if len(sys.argv) != 3:
        sys.stderr.write(
            "usage: gen_errors.py <szerrors.json> <output sz_error_map.inc>\n")
        return 2

    errors_json_path = sys.argv[1]
    output_path = sys.argv[2]

    with open(errors_json_path, "r", encoding="utf-8") as handle:
        errors = json.load(handle)

    if not isinstance(errors, dict) or not errors:
        sys.stderr.write(
            f"error: {errors_json_path} did not contain a non-empty object\n")
        return 1

    rows = []
    for code_str, info in errors.items():
        klass = info.get("class")
        if klass is None:
            sys.stderr.write(f"error: entry {code_str} missing 'class'\n")
            return 1
        if klass not in CLASS_TO_ENUM:
            sys.stderr.write(
                f"error: unknown error class {klass!r} for code {code_str} "
                f"(update CLASS_TO_ENUM in gen_errors.py)\n")
            return 1
        enum_name = CLASS_TO_ENUM[klass]
        if enum_name == "Base":
            # Base SzException is the implicit default; omit (matches C# mapper).
            continue
        rows.append((int(code_str), enum_name))

    rows.sort(key=lambda r: r[0])

    lines = [
        "// GENERATED FILE -- DO NOT EDIT.",
        f"// Generated by tools/gen_errors.py from {errors_json_path}",
        "// Sorted {errno, SzErrorClass} pairs. Codes mapping to the base",
        "// SzException are omitted (base is the default for unmapped codes).",
    ]
    for code, enum_name in rows:
        lines.append(f"{{{code}, SzErrorClass::{enum_name}}},")

    with open(output_path, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines))
        handle.write("\n")

    return 0


if __name__ == "__main__":
    sys.exit(main())
