#!/usr/bin/env python3
"""Generate include/senzing/sdk/SzFlags.hpp from the installed szflags.json.

No flag values are hardcoded in C++ -- every named constant and its int64 value
come from the Senzing-provided szflags.json (default
/opt/senzing/er/sdk/szflags.json). Names use the PascalCase `altSymbol` field so
they mirror the C# SDK character-for-character.

Usage: gen_flags.py <szflags.json> <output SzFlags.hpp>
"""

import json
import sys


# Aliases that the C# SDK exposes but that are not standalone entries in
# szflags.json (they are defined purely in terms of another flag). These are
# derived from existing constants -- NOT hardcoded magic values -- so they are
# emitted as references to those constants. Keep this list minimal and only for
# constants the public C# API (SzFlags.cs) defines as a direct alias.
DERIVED_ALIASES = {
    # C#: public const SzFlag SzRedoDefaultFlags = SzNoFlags;
    "SzRedoDefaultFlags": "SzNoFlags",
}


def main() -> int:
    if len(sys.argv) != 3:
        sys.stderr.write(
            "usage: gen_flags.py <szflags.json> <output SzFlags.hpp>\n")
        return 2

    flags_json_path = sys.argv[1]
    output_path = sys.argv[2]

    with open(flags_json_path, "r", encoding="utf-8") as handle:
        entries = json.load(handle)

    if not isinstance(entries, list) or not entries:
        sys.stderr.write(
            f"error: {flags_json_path} did not contain a non-empty array\n")
        return 1

    names_seen = set()
    lines = []
    for entry in entries:
        name = entry.get("altSymbol")
        value = entry.get("value")
        symbol = entry.get("symbol", "")
        if not name or value is None:
            sys.stderr.write(
                f"error: entry missing altSymbol/value: {entry!r}\n")
            return 1
        if name in names_seen:
            sys.stderr.write(f"error: duplicate altSymbol {name!r}\n")
            return 1
        names_seen.add(name)
        # int64 literal; values fit in signed 64-bit.
        lines.append(
            f"/// {symbol}\n"
            f"inline constexpr SzFlags {name}{{static_cast<int64_t>"
            f"({value}LL)}};")

    alias_lines = []
    for alias, target in DERIVED_ALIASES.items():
        if alias in names_seen:
            # Already provided directly by the JSON; no alias needed.
            continue
        if target not in names_seen:
            sys.stderr.write(
                f"error: alias {alias!r} targets unknown flag {target!r}\n")
            return 1
        alias_lines.append(
            f"/// Alias (C# SzFlags.cs): {alias} == {target}\n"
            f"inline constexpr SzFlags {alias}{{{target}}};")

    body = "\n".join(lines)
    aliases = "\n".join(alias_lines)

    header = f"""// GENERATED FILE -- DO NOT EDIT.
// Generated by tools/gen_flags.py from {flags_json_path}
// Source of truth for all flag values is the Senzing-provided szflags.json.
#ifndef SENZING_SDK_SZFLAGS_HPP
#define SENZING_SDK_SZFLAGS_HPP

#include <cstdint>

namespace senzing::sdk {{

/// Strongly-typed 64-bit bitmask mirroring the C# `SzFlag`/`SzFlags` surface.
/// Wraps an int64_t so flag combination is type-safe and explicit.
class SzFlags {{
public:
    constexpr SzFlags() noexcept = default;
    constexpr explicit SzFlags(int64_t value) noexcept : value_(value) {{}}

    /// The raw int64 bitmask value as consumed by the native engine.
    [[nodiscard]] constexpr int64_t Value() const noexcept {{ return value_; }}

    constexpr SzFlags operator|(SzFlags other) const noexcept {{
        return SzFlags{{value_ | other.value_}};
    }}
    constexpr SzFlags operator&(SzFlags other) const noexcept {{
        return SzFlags{{value_ & other.value_}};
    }}
    constexpr SzFlags operator^(SzFlags other) const noexcept {{
        return SzFlags{{value_ ^ other.value_}};
    }}
    constexpr SzFlags operator~() const noexcept {{
        return SzFlags{{~value_}};
    }}
    constexpr SzFlags& operator|=(SzFlags other) noexcept {{
        value_ |= other.value_;
        return *this;
    }}
    constexpr SzFlags& operator&=(SzFlags other) noexcept {{
        value_ &= other.value_;
        return *this;
    }}
    constexpr SzFlags& operator^=(SzFlags other) noexcept {{
        value_ ^= other.value_;
        return *this;
    }}

    constexpr bool operator==(SzFlags other) const noexcept {{
        return value_ == other.value_;
    }}
    constexpr bool operator!=(SzFlags other) const noexcept {{
        return value_ != other.value_;
    }}

    /// True if any bit is set.
    [[nodiscard]] constexpr explicit operator bool() const noexcept {{
        return value_ != 0;
    }}

private:
    int64_t value_{{0}};
}};

// ---- Named flag constants (PascalCase, mirroring the C# SDK) ----
{body}

// ---- Derived aliases (defined by the C# SDK in terms of other flags) ----
{aliases}

}}  // namespace senzing::sdk

#endif  // SENZING_SDK_SZFLAGS_HPP
"""

    with open(output_path, "w", encoding="utf-8") as handle:
        handle.write(header)

    return 0


if __name__ == "__main__":
    sys.exit(main())
